### ISSUE TITLE
pdf conversion script errors

### ISSUE THREAD

**Issue by git-madhav** [hackhuntsville/madisoncrimes#5]
I found the latest pdf to text conversion has still errors. I found another tool "pdftotext" 

with pdftotext -layout <pdfname> <textfilename> gives pretty good results. 

Nathan, can you check this on your end? if you like it I can use this for batch processing. It seems pretty fast.

**Comment by git-madhav** [comment]
FYI: I got "pdftotext" from : sudo apt-get install poppler-utils

**Comment by mjcarroll** [comment]
Can you check in some example text from the conversion?

Also, @git-madhav, your git user and git e-mail aren't set, so you don't render properly in github.
See this link: https://help.github.com/articles/set-up-git/

**Comment by git-madhav** [comment]
I have converted all pdfs uploaded converted text and parsed .csv file to git. Conversion took less than 20 sec. 
Next step is to get geocoding!

**Comment by mjcarroll** [comment]
:+1: We can close this then.
